### ISSUE TITLE
Symlinks not replicated in temporary directory

### ISSUE THREAD

**Issue by gtristan** [omarkohl/pytest-datafiles#1]
I'm using pytest-datafiles to test [BuildStream](https://gitlab.com/BuildStream/buildstream), which is a build tool and as such does a lot of filesystem manipulation (naturally, we also have a lot of test cases which need to manipulate files mirrored outside of the git directory).

For us, the difference between a symlink to a file, and a copy of the said file, is an important difference; we need to test build scenarios where there are symlinks.

Currently our problem is that, if I commit symlinks to my test data dirs in git, and then use `@pytest.mark.datafiles()` to test with a directory that contains symlinks, the symlinks just dont appear in the test environment. Instead copies of the symlink targets are created.

Currently I have some ugly workarounds in place which create the required symlinks in the tmpdir manually in advance of testing.

**Comment by omarkohl** [comment]
Thanks for the feedback! I'll have a look.

**Comment by omarkohl** [comment]
Sorry it took me a while, but it should be fixed now. You can try it with the current 'master' branch or wait for the next release which will probably happen today or the next few days.

**Comment by omarkohl** [comment]
This has been released with pytest-datafiles version 2.0
