### ISSUE TITLE
ScopeMismatch error when using datafiles in a module-scoped fixture

### ISSUE THREAD

**Issue by jpsnyder** [omarkohl/pytest-datafiles#12]
I am running into an issue where I get a "ScopeMismatch" error if I try to use datafiles to create another fixture with a different scope than "function".

I want the scope to be "module" based because I would like to keep the database open for all tests since loading the database is time consuming.

Here is a simplified example of what I am trying to do:

```python
@pytest.fixture(scope="module")
@pytest.mark.datafiles(TEST_DATA_DIR / "image.png")
def image_db(datafiles):
    """Loads image.png into database and returns database entry"""
   with database():
      database.add(datafiles / "image.png")
      for db_entry in database.query_images():
         yield db_entry
         break
```

```
test setup failed
ScopeMismatch: You tried to access the 'function' scoped fixture 'datafiles' with a 'module' scoped request object, involved factories
```

Any help is a appreciated.

**Comment by omarkohl** [comment]
I guess the error message says it all. 'datafiles' is function-scoped whereas your fixture is module-scoped. I do not know if it's possible to solve this. Maybe datafiles could be converted into a module-scoped fixture, but I do not know what the advantages or disadvantages would be. I don't have the time to investigate this.

**Comment by jpsnyder** [comment]
No worries, I totally forgot I made this issue or what project I was working on that needed this.
I think I just ended up rolling my own fixture.

Feel free to close this issue.
