### ISSUE TITLE
Change in order of retrieval

### ISSUE THREAD

**Issue by MajorCarrot** [omarkohl/pytest-datafiles#15]
I want to test two files like so:

```
@pytest.mark.datafiles(os.path.join(FIXTURE_DIR, '2019_DPD.txt'),
                       os.path.join(FIXTURE_DIR, 'expected_DPD.csv'))
def test_dpd_to_dataframe(datafiles):
    path_to_data_file = str(datafiles.listdir()[0])
    # Do stuff

    expected_dpd_df = pd.read_csv(str(datafiles.listdir()[1]))
    # Do other stuff

    assert dpd_df.equals(expected_dpd_df)
```

and this will work only if file1 and  file2 are stored in that order (The functions I am testing with are different and the files, hence, are different)

Is there any way to make sure that datafiles.listdir() returns the files in the exact same order and not switch it. (Like it is happening now)

**Comment by omarkohl** [comment]
'datafiles' represents a directory and listdir() only lists the content of that directory in no particular order. The Python *os.listdir()* documentation states:

```
 The list is in arbitrary order
```

You should separate the different file types into subdirectories inside your FIXTURE_DIR. Then you can choose the first item in one subdirectory or the first item in the second one.

```
@pytest.mark.datafiles(os.path.join(FIXTURE_DIR, 'test_dpd'),
                       os.path.join(FIXTURE_DIR, 'expected_dpd'),
                       keep_top_dir=True,
                       )
def test_dpd_to_dataframe(datafiles):
    test_file = str((datafiles / 'test_dpd').listdir()[0])
    expected_file = str((datafiles / 'expected_dpd').listdir()[0])
    ...
```
