### ISSUE TITLE
use in combination with @fixture

### ISSUE THREAD

**Issue by hans-d** [omarkohl/pytest-datafiles#22]
```
@pytest.fixture
@pytest.mark.datafiles('/tmp/big_files/film1.mp4')
def lots_of_files(datafiles):
    pass
```

currently not providing the files I'm looking for

**Comment by omarkohl** [comment]
Can you elaborate what you are trying to achieve? I guess one of the examples already shows a way of achieving this:

```python
# more details in `examples/example_3.py`

ALL_IMGS = pytest.mark.datafiles(
    FIXTURE_DIR / 'img1.jpg',
    FIXTURE_DIR / 'img2.jpg',
    FIXTURE_DIR / 'img3.jpg',
)

@ALL_IMGS
def test_something1(datafiles):
    # ...
```

**Comment by flacoste** [comment]
I have the same request.

My use case is that I'm defining a fixture that will be used by several tests that requires a file in its constructor.

Think of something like:

```
class MyRepository:
    def __init__(self, repodir):
          # ...

@pytest.fixture
@pytest.mark.datafiles(FIXTURE_DIR / 'testrepo', keep_top_dir=True)
def testrepo(datafiles):
    return MyRepository(datafiles / 'testrepo')

def test_repo_func(testrepo):
     # Test some function on MyRepository

```

**Comment by flacoste** [comment]
I looked a bit into this, and it seems that marks shouldn't be used on fixture. There is [this issue](https://github.com/pytest-dev/pytest/issues/3664) on pytest about raising an exception in such cases. 

That means that the mark API cannot be used for this use-case :-/ So supporting that use-case would require an API change. One possible solution would be to add a method to the Path object returned by the fixture. That method could be use to add files to the temporary directory. So the above use case would look like:

```
@pytest.fixture
def testrepo(datafiles):
    datafiles.add(FIXTURE_DIR / 'testrepo', keep_top_dir=True)
    return MyRepository(datafiles / 'testrepo')
    # Or even:
   return MyRepository(datafiles.add(FIXTURE_DIR / 'testrepo', keep_top_dir=True)
```

(And yes, fixtures composition works fine with tmp_path.)

Thoughts?

**Comment by flacoste** [comment]
Another possibility would be to mirror the tmp_path_factory idiom and add a datafiles_factory fixture that can be used from fixtures and where one would add files and directory to it using method calls.

**Comment by omarkohl** [comment]
I'm not sure I understand how it should work with a datafiles_factory fixtures. The big problem in all cases is how to tell the fixture which files to actually copy to the temp dir. That is what the _mark_ is being used for, which seems to be incompatible with fixtures according to the link to the issue you submitted.

The `datafiles.add()` method would do nothing more than copy the files to the temporary directory, right?

But then I wonder, why not use a `tmp_path` directly?

So something like this:

```python
class MyRepository:
    def __init__(self, repodir):
          # ...

@pytest.fixture
def testrepo(tmp_path):
    shutil.copytree(FIXTURE_DIR / 'testrepo', tmp_path)
    return MyRepository(tmp_path)

def test_repo_func(testrepo):
     # Test some function on MyRepository
```
