### ISSUE TITLE
Paths relative to test files

### ISSUE THREAD

**Issue by neighthan** [omarkohl/pytest-datafiles#6]
It seems that if relative paths are given in the decorator, they're assumed to be relative to the directory where you ran `pytest` from. To me, it makes more sense to have the paths relative to the file that defines the tests that are running. Breaking backwards compatibility is problematic, but what would you think of having a flag which can be used to make the paths relative to the test itself?

**Comment by omarkohl** [comment]
What you are asking for _feels_ unusual to me. I think in general relative paths are assumed to be relative to the executor not relative to the files being executed. At least in the UNIX/Linux world, which is the one I am more familiar with. If you disagree with this could you maybe provide some examples where this is done differently?

The *Example 2* from the README also solves your question:

```python
FIXTURE_DIR = os.path.join(
    os.path.dirname(os.path.realpath(__file__)),
    'test_files',
    )

@pytest.mark.datafiles(
    os.path.join(FIXTURE_DIR, 'img1.jpg'),
    os.path.join(FIXTURE_DIR, 'img2.jpg'),
    os.path.join(FIXTURE_DIR, 'img3.jpg'),
    )
def test_find_borders(datafiles):
    for img in datafiles.listdir():
        print(img)
        #assert process(img) == some_expected_value
```

**Comment by neighthan** [comment]
I certainly agree that paths given on the command line are assumed to be relative to the cwd. However, I think it's not uncommon to have _internal_ paths be relative to the file where those paths are written. For example, in Python you can do imports with relative paths which can be handy within a package. It makes sense when you're writing a test that you encode where the test files are; it would be odd, at least in most cases, if the test files were looked for in a different directory based on where the user was executing the tests from. Your examples back this up - all of them use absolute paths, and all of those absolute paths but one (I think) are based on a relative path from the test file itself. Those examples would thus be simplified a decent bit by allowing relative paths. Again, for backwards compatibility's sake, I don't think this should be changed by default, but I could either have a flag like `relative` (defaults to `False`, can be set `True` to be relative to the directory of the test script) or have a directory like `relative_to=None` (if `None`, then relative to the cwd; otherwise, relative to the directory given). Then you could do either:

```python
@pytest.mark.datafiles('img1.jpg', 'img2.jpg', 'img3.jpg', relative=True)
def test_find_borders(datafiles):
    for img in datafiles.listdir():
        print(img)
        #assert process(img) == some_expected_value
```

or

```python
from pathlib import Path
FIXTURE_DIR = Path(__file__).parent.resolve() / "test_files"

@pytest.mark.datafiles('img1.jpg', 'img2.jpg', 'img3.jpg', relative_to=str(FIXTURE_DIR))

def test_find_borders(datafiles):
    for img in datafiles.listdir():
        print(img)
        #assert process(img) == some_expected_value
```

**Comment by enelytics** [comment]
I new to Python and new to testing also, so I'm doubly in need of help.
I can get this to module to work in the test file, but I can't seem to get the same success if placed in conftest.py

# in the file 'test_inv_scan.py'
@pytest.mark.datafiles('../images/company_specific/invoice_identifiers/')
def test_is_known_company(datafiles):
    for img in datafiles.listdir():
        print(img)
    #assert something

The above works 

The following will not work:
-----
# in the file conftest.py
@pytest.mark.datafiles('../images/company_specific/invoice_identifiers/')
def inv_ids(datafiles):
    return datafiles
 
# in the file 'test_inv_scan.py'
def test_is_known_company_2(inv_ids):
    path = str(inv_ids)
    print(os.listdir(path)) .     #this shows empty
    for img in inv_ids.listdir():
        print(img)
    # assert something

----
folder structure:
project/
+-- images/
+--tests/
    +-- test_inv_scan.py
    +--conftest.py

Can you spot anything that is preventing using the fixture from the conftest file?

**Comment by konoufo** [comment]
> I am new to Python and new to testing also, so I'm doubly in need of help.
> I can get this to module to work in the test file, but I can't seem to get the same success if placed in conftest.py
> (also, I am not doing well with Markdown either, sorry)
> 
> ```
> @pytest.mark.datafiles('../images/company_specific/invoice_identifiers/')
> def test_is_known_company(datafiles):
>     # print('The datafiles folder is -----> : ' + str(datafiles))
>     print('Testing going on ________')
>     path = str(datafiles)
>     print(os.listdir(path))
>     for img in datafiles.listdir():
>         print(img)
>     assert True
> ```
> 
> The above works
> 
> The following will not work:
> --- in the file conftest.py
> 
> ```
> @pytest.mark.datafiles('../images/company_specific/invoice_identifiers/')
> def inv_ids(datafiles):
>     return datafiles
> ```
> 
> ---in the file 'test_inv_scan.py'
> 
> ```
> def test_is_known_company_2(inv_ids):
>     path = str(inv_ids)
>     print(os.listdir(path))      #this shows empty
>     for img in inv_ids.listdir():
>         print(img)                    # nothing prints of course
>     # assert something
> ```
> 
> folder structure:
> 
> ```
> project/
> +-- images/
> +--tests/
>     +-- test_inv_scan.py
>     +--conftest.py
> ```
> 
> Can you spot anything that is preventing using the fixture from the conftest file?

You should mark `def inv_ids` as a fixture, for it to be picked up by pytest.
```
@pytest.fixture
@pytest.mark.datafiles('../images/company_specific/invoice_identifiers/')
def inv_ids(datafiles):
    return datafiles
```

**Comment by omarkohl** [comment]
I am closing this issue because even though I can see that this could be useful it is contrary to the usual way of handling paths in Python and it is possible to use paths relative to the test file itself with the technique described above.

Just to give another example. When writing a regular Python program (or pytest test) if it includes something like this:

```python
with open('some/path/file.txt) as f:
    read_data = f.read()
```

Then the path `some/path/file.txt` will be relative to the executor not relative to the Python file.

@ra-jamieson please open a new issue if you still have problems because you problem doesn't look related to the current issue.
